# Site Info
title: Codinfox Lanyon
tagline: '매일 쓰고 싶은 개발 일기장'
description: 'A Jekyll theme adapted from <a href="http://lanyon.getpoole.com/" target="_blank">Lanyon</a>. Made by <a href="http://codinfox.github.io" target="_blank">@codinfox</a>.'
baseurl: ""
url: http://skins346.github.io
logo: '/public/logo.png'

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 5
paginate_path: '/개발/page:num'
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: Martin
  description: <strong>안드로이드 앱 개발</strong>을 주로 하고 <strong>기타</strong> 치는 걸 좋아합니다.
  gravatar: 3c2986ad7ac1f2230ea3596f44563328 # md5 hash of your email address
  contact:
    linkedin:  https://www.linkedin.com/in/young-song-kim-89590714a/
    github:    https://github.com/skins346
    facebook:  https:/www.facebook.com/skins346
    email:     http://www.google.com/recaptcha/mailhide/d?k=01I3lZFiZYng9N3QxYEtsDaQ==&c=31wAnZkuKqcG0ATAqJN8Z3ln5kkYLA9TwkGc-IbygpM=

# Navigation (2nd level links supported)
nav:
  Home:           
    - '/'
  개발:           
    - '/개발/'
    - { Java: '/개발/Java/' }
    - { RxJava: '/개발/RxJava/' }
    - { Kotlin: '/개발/Kotlin/'}
    - { Node.js: '/개발/Node.js/'}
    - { JavaScript: '개발/JavaScript.js/'}
  About:          
    - '/about/'
  Github Project: 
    - 'http://github.com/skins346'

# Where are tags and categories displayed
Java_page: '/개발/Java/'
RxJava_page: '/개발/RxJava/'
Kotlin_page: '/개발/Kotlin/'
Node.js_page: '/개발/Node.js/'
JavaScript_page: '/개발/JavaScript/'

hero:
  image: /public/img/home.jpeg
  caption: 2017.08.29

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: 'UA-00000000-1' # leave blank if you don't want google analytics
disqus_short_name: 'your_short_name' # leave blank if you don't want disqus

